### ISSUE TITLE
Update of a mod (FNF NEO 3.0) (PICOS SCHOOL/FRIDAY NIGHT SHOOTIN’ 3.0) (D-SIDES)

### ISSUE THREAD

**Issue by ThegamemixYT** [obscurerev/FNF-Mods-Web-Browser-Install#2]
I know w8.snokido.com probably does not have it but I’m pretty sure gamaverse.com has it so if you could can you please add Neo 3.0? Even know i wont be able to play it would be nice for other users of this site to be able to play Neo 3.0 and would really enjoy it so if you could that would be wonderful.  Thanks in advance -ThegamemixYT

**Comment by ThegamemixYT** [comment]
K

**Comment by obscurerev** [comment]
it's not available online yet
